# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2dee1d5fe98ef5ac6b4a2e9ee4d9adbd9d25a5355a23581330cb5ec411228604bec69c86e29b526fa00575d4ea981aceecf12796873856c61394fb2cdf432211

test:
  secret_key_base: e314ee6efbddaec348520f67543bb714e9277b91f5a306e7b722a1536cc5897dd210100e99bf06a4fe2726f2dc92419bf2885e56c9129c10a7518b4d5ee81ccc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
